### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by rchiossi**

### CODE REVIEW

**Comment by guiccbr** [comment]
Thanks, Chiossi.

After taking a closer look, I noted that letting recvfrom() responsible for initializing remote_addr might not be a good idea for two reasons:
1. If for some reason sendto() is called before a valid response from mavproxy, it will be called with an unitialized remote_addr.
2. If another remote (not mavproxy) sends a message and we received it with recvfrom(), it will replace the remote_addr, causing the next calls to sendto() to send messages to an unexpected remote.

I think it would be safer to have remote_addr properly initialized and passing NULL to recvfrom as follows:

`
ssize_t bytes_recvd = recvfrom(sock, (void *)data_recv, BUFFER_LEN, 0, NULL, NULL);
`

What do you guys think?

**Comment by rchiossi** [comment]
Nop, you can't do that. Actually your previous initialization was wrong, it wasn't using that address/port. If someone pings that port before mavproxy, the address will be corrected once mavproxy starts the communication, since remote_addr is always overwritten. I also checked, and there is no way in your code for sendto() to be called before recvfrom().

**Comment by guiccbr** [comment]
I see. The previous initialization was indeed wrong. We will need to fix it if we choose to use recvfrom() with NULL.

In case someone pings that port first, we might be pinging someone we don't necessarily want to ping if sendto() is called while remote_addr has not been properly corrected.

And I agree that in the current implementation remote_addr will be always initialized before sendto(). However, I'm afraid it might be some source of bug in the future if we change something and forget that remote_addr needs to be defined first.

**Comment by rchiossi** [comment]
Ok, I see your point, but there are a few things we need to consider here.

By definition, this is a server, which mean it will not starts connections, only react to then. If we ever change this behavior, that's when we will need to specify where to connect and by consequence, initialize remote addr.

Still, even in the current setup, you may want to check if remote addr has been initialized or not before usage. You could indeed check for a variable like "is_initialized" before attempting to use a sendto(), but looking at the code, it seems redundant, since data_to_send_len serves the same purpose at the initial state of mavserver.

**Comment by guiccbr** [comment]
Ok. I've been convinced. Let's merge!

**Pull request closed without merging**
